# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20170904_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAttributes',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
