# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0442\u043e\u0432\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u041a\u043e\u0434 (\u0410\u0440\u0442\u0438\u043a\u0443\u043b)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430-\u043c\u0435\u0442\u043a\u0430'),
        ),
    ]
