# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170912_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='external_link',
            field=models.URLField(blank=True, help_text='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0442\u043e\u0432\u0430\u0440 \u0441 \u0441\u0430\u0439\u0442\u0430 missmexx.ru', verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0442\u043e\u0432\u0430\u0440'),
        ),
    ]
